### PR TITLE
fix: ID sent by Publisher as integer

### PR DESCRIPTION
**Pull request by douglasmuraoka**
The ID field should be sent as a string. AWS SDK doesn't recognizes it and throws the following error: "Missing required key 'Id' in params.Entries[0]".

### CODE REVIEW

**Comment by acinader** [comment]
@douglasmuraoka so I don't even use this package myself.  I built it to test something @flovilmart had built.  I'd like to add you as a maintainer if you'd be interested.  I'd still review pull requests.

**Comment by douglasmuraoka** [comment]
@acinader yes, I think It could make things easier, I appreciate It. Thank you! :)

**Comment by douglasmuraoka** [comment]
@acinader when possible, could you release a new version on npm? I'm needing it for my current task. Thank you!

**Comment by flovilmart** [comment]
@douglasmuraoka you should be able to use the master branch for the dependency in your package.json.

**Comment by douglasmuraoka** [comment]
@flovilmart thanks for the tip.

**Comment by acinader** [comment]
@douglasmuraoka I added you with write access to this repo.  Thanks.

@flovilmart I merged your pr: https://github.com/parse-community/parse-server-sqs-mq-adapter/pull/17

so now there are two packages on npm:

the old one: https://www.npmjs.com/package/parse-server-sqs-mq-adapter which is on 1.3.0

and the new one: https://www.npmjs.com/package/@parse/sqs-mq-adapter which is on 1.3.2

so @flovilmart is there something I need to do to kill the old one or something??

**Comment by flovilmart** [comment]
You can use npm deprecate to indicate `parse-server-sqs-mq-adapter` is replaced by `@parse/sqs-mq-adapter`

https://docs.npmjs.com/cli/deprecate

**Comment by acinader** [comment]
thanks.  done.

**Pull request merged**
